export const advices = [
    "Domina HTML y CSS: Son la base de cualquier sitio web.",
    "Aprende JavaScript: Es esencial para agregar interactividad a tus páginas.",
    "Usa un sistema de control de versiones: Git es imprescindible para el desarrollo colaborativo.",
    "Familiarízate con frameworks: Aprende al menos uno como React, Angular o Vue.js.",
    "Practica la escritura de código limpio: Mantén tu código legible y bien estructurado.",
    "Optimiza la velocidad de carga: Los usuarios abandonan sitios lentos, utiliza técnicas de optimización.",
    "Aprende sobre SEO: Una buena optimización para motores de búsqueda es clave para el éxito.",
    "Conoce las herramientas de depuración: Usa DevTools de tu navegador para solucionar problemas.",
    "Domina Flexbox y Grid: Son esenciales para crear diseños responsivos.",
    "Usa preprocesadores CSS: Sass y Less pueden facilitarte el trabajo con CSS.",
    "Desarrolla para accesibilidad: Asegúrate de que tu sitio sea usable para personas con discapacidades.",
    "Implementa pruebas unitarias: Asegúrate de que tu código funciona como esperas.",
    "Comprende la arquitectura web: Aprende cómo funciona el frontend y backend.",
    "Maneja bien las APIs: Aprende a consumir y crear APIs RESTful.",
    "Crea sitios responsivos: Asegúrate de que tu sitio se vea bien en cualquier dispositivo.",
    "Usa herramientas de automatización: Gulp y Webpack pueden ahorrarte tiempo en tareas repetitivas.",
    "Aprende sobre bases de datos: Conoce cómo funcionan y cómo conectarlas con tu sitio.",
    "Familiarízate con servidores y hosting: Entiende cómo desplegar tu sitio en la web.",
    "Mantén la seguridad en mente: Protege tu sitio contra ataques comunes como XSS y SQL Injection.",
    "Mejora tus habilidades de diseño: Aunque seas desarrollador, entender de diseño es un plus.",
    "Aprende sobre DevOps: Conoce cómo integrarte mejor en un equipo que sigue metodologías ágiles.",
    "Optimiza imágenes y recursos: Reducir el tamaño de archivos mejora la velocidad de carga.",
    "Documenta tu código: Facilita el mantenimiento y la colaboración futura.",
    "Conoce las PWA: Las aplicaciones web progresivas pueden ofrecer una mejor experiencia a los usuarios.",
    "Usa iconos y tipografías optimizados: Opta por soluciones que no ralenticen tu sitio.",
    "Mantente actualizado: El desarrollo web evoluciona rápidamente; siempre hay algo nuevo que aprender.",
    "Involúcrate en la comunidad: Participa en foros, meetups y conferencias para aprender y crecer.",
    "Aprende a leer la documentación: La documentación oficial es tu mejor amiga.",
    "Crea y mantén un portafolio: Muestra tus habilidades a posibles empleadores o clientes.",
    "Trabaja en proyectos personales: Experimentar por tu cuenta te ayudará a aprender y mejorar.",
    "Domina el Responsive Design: Usa media queries para adaptar el diseño a distintos tamaños de pantalla.",
    "Usa animaciones con moderación: Pueden mejorar la experiencia del usuario, pero sin exagerar.",
    "Conoce los principios de UX/UI: Una buena experiencia de usuario es clave para el éxito de un sitio.",
    "Ten en cuenta la escalabilidad: Piensa en cómo tu sitio puede crecer y adaptarse en el futuro.",
    "Implementa un sistema de comentarios: Los comentarios en tu código facilitan su comprensión.",
    "Aprende sobre CI/CD: La integración y entrega continua son fundamentales en proyectos grandes.",
    "Domina el uso de GitHub: Es una plataforma clave para el trabajo en equipo y la gestión de proyectos.",
    "Haz refactorización constante: Mantén tu código actualizado y eficiente.",
    "Familiarízate con las tendencias: Aprende sobre tecnologías emergentes como WebAssembly o GraphQL.",
    "Disfruta el proceso: El desarrollo web es un campo amplio y apasionante; disfruta cada paso del aprendizaje."
  ];